package HelloDrools
  
rule "check for valid docs"
   when
      $doc: Document( checkValid() == true) 
   then
      if($doc.docType() == "dependent")
        insertLogical(new MatchableDependentDocument($doc));
      else
        insertLogical(new MatchableRootDocument($doc));
end

rule "foo match"
   when
      $root: MatchableRootDocument()
      $match: MatchableDependentDocument( 
        $root.doc.args().get("foo") == $match.doc.args().get("foo") )
   then
      insertLogical(new Match($root, $match));
end
